/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppButton: typeof import('./components/atoms/AppButton/AppButton.vue')['default']
    AppIcon: typeof import('./components/atoms/AppIcon/AppIcon.vue')['default']
    AppTest: typeof import('./components/AppTest.vue')['default']
    BoxInfo: typeof import('./components/atoms/BoxInfo/BoxInfo.vue')['default']
    CardComponent: typeof import('./components/molecules/CardComponent/CardComponent.vue')['default']
    FormCheckbox: typeof import('./components/atoms/Form/FormCheckbox/FormCheckbox.vue')['default']
    FormData: typeof import('./components/molecules/FormData/FormData.vue')['default']
    FormInput: typeof import('./components/atoms/Form/FormInput/FormInput.vue')['default']
    FormLabel: typeof import('./components/atoms/Form/FormLabel/FormLabel.vue')['default']
    FormLegend: typeof import('./components/atoms/Form/FormLegend/FormLegend.vue')['default']
    FormRadio: typeof import('./components/atoms/Form/FormRadio/FormRadio.vue')['default']
    FormRadioGroup: typeof import('./components/atoms/Form/FormRadioGroup/FormRadioGroup.vue')['default']
    FormSelect: typeof import('./components/atoms/Form/FormSelect/FormSelect.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LoadingBar: typeof import('./components/atoms/LoadingBar/LoadingBar.vue')['default']
    MainBanner: typeof import('./components/molecules/MainBanner/MainBanner.vue')['default']
    PageAnimation: typeof import('./components/atoms/PageAnimation/PageAnimation.vue')['default']
    PageContent: typeof import('./components/molecules/PageContent/PageContent.vue')['default']
    PageHeader: typeof import('./components/molecules/PageHeader/PageHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabsWrapper: typeof import('./components/molecules/TabsWrapper/TabsWrapper.vue')['default']
    TextBoxMD: typeof import('./components/atoms/TextBoxMD/TextBoxMD.vue')['default']
    TheAvatar: typeof import('./components/atoms/TheAvatar/TheAvatar.vue')['default']
    TheCounter: typeof import('./components/readme/TheCounter.vue')['default']
    TheNavigation: typeof import('./components/TheNavigation.vue')['default']
    TheReactive: typeof import('./components/readme/TheReactive.vue')['default']
    TheTab: typeof import('./components/atoms/TheTab/TheTab.vue')['default']
    TheWelcome: typeof import('./components/TheWelcome.vue')['default']
    TimerVisit: typeof import('./components/atoms/TimerVisit/TimerVisit.vue')['default']
    WelcomeItem: typeof import('./components/WelcomeItem.vue')['default']
  }
}
